name: Run jest tests
on: [push, pull_request]

jobs:
  run_unit_tests:
    name: Run your unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 14
      
      - name: Install Node dependencies
        run: npm install

      - name: Run the tests
        run: npm run test
